### ISSUE TITLE
SOCKS5 proxy blocking divested.dev

### ISSUE THREAD

**Issue by WeirDan76** [mullvad/dns-adblock#46]
Hi, 
It's not really the DNS filtering from the app, but your SOCKS5 proxy (at least in Switzerland) is blocking the website divested.dev, which I don't think is warranted. It'd be great to be able to use as it provides filter lists for uBO.
Thanks!

**Comment by oskaralmlov** [comment]
Hello! 
Thanks for reaching out and reporting this error. 

I've attempted to recreate the issue you are describing on multiple relays in Switzerland but I have not encountered any problems with connecting to that service. 

We don't do any other blocking for SOCKS so that should not be part of the equation here. However, when you connect through mullvad via SOCKS you end up using a different exit IP than your "normal" VPN traffic, which might affect connectivitiy in some ways. It might be that either;
A) the administrators of that service temporarily blocked the relays you were connecting through. This happens from time to time for various reasons. The administrators might for example confuse our relays with an abusive user due to the amount of requests coming from 1 IP. 
B) there was some temporary connectivity issue to that service from our site in Switzerland.

This sort of question is better directed at our support team (support@mullvad.net) since they have a better overview of ongoing issues and other user error reports. They'll be able to provide better help and answers than us techies :) 

Have a nice day!

**Comment by WeirDan76** [comment]
Well noted @oskaralmlov, thanks for the reply. On my end, there is no doubt that the issue came via/through/with the SOCKS connection, as this is the one single parameter that makes a difference between connecting and not connecting (I tried with several browsers and profiles, and, within the problematic profile, turning the proxy on/off is the only thing that allows connection). Of course, beyond this, I cannot say exactly where the issue lies. I'll reach out to the support service.
